variables:
  BUILD_VERSION: 1.0.31.2
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:${BUILD_VERSION}
  DOCKER_DEV_IMAGE_TAG: monfex/simple-trading-web-terminal:${BUILD_VERSION}-${CI_COMMIT_REF_NAME}
  K8S_DEV_APP_SELECTOR: simple-trading-web-terminal
  K8S_DEV_NAMESPACE: simple-trading-dev
  K8S_DEV_CONTEXT: SimpleTradingDev
  K8S_TEST_APP_SELECTOR: simple-trading-web-terminal
  K8S_TEST_NAMESPACE: simple-trading
  K8S_TEST_CONTEXT: simple-trading-test-kube
  BUILD_FOLDER: wwwroot
  KUBERNETES_APP_DEV_SELECTOR_NAME: simple-trading-web-terminal
  KUBERNETES_APP_TEST_SELECTOR_NAME: web-terminal

stages:
  - test
  - build
  - publish
  - publish-kubernetes

prebuild-test:
  stage: test
  image: node:14.6.0
  variables:
    API_AUTH_STRING: ${TEST_API_AUTH_STRING}
    TRADING_URL: ${TEST_TRADING_URL}
  script:
    - npm i
    - npm test
  only:
    - test

prebuild-prod:
  stage: test
  image: node:14.6.0
  variables:
    API_AUTH_STRING: ${MASTER_API_AUTH_STRING}
    TRADING_URL: ${MASTER_TRADING_URL}
  script:
    - npm i
    - npm test
  only:
    - master

build-dev:
  stage: build
  image: node:14.6.0
  script:
    - pwd
    - ls -la
    - npm -v
    - node -v
    - npm i
    - npm run buildTest
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - development

build-test:
  stage: build
  image: node:14.6.0
  script:
    - npm i
    - npm run buildTest
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - test


build-master:
  stage: build
  image: node:14.6.0
  script:
    - npm i
    - npm run buildProd
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - master

publish-prod:
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - master

publish-test:
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}
  image: docker:latest
  only:
    - test

publish-dev:
  stage: publish
  tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG}
  image: docker:latest
  only:
    - development

publish-kubernetes-dev:
  stage: publish-kubernetes
  image: simpletrading.azurecr.io/monfex/simple-trading-kubectl:latest
  services:
    - docker:dind
  before_script:
    - kubectl config use-context $KUBERNETES_DEV_CONTEXT
  script:
    - kubectl set image deployments/${KUBERNETES_APP_DEV_SELECTOR_NAME} ${KUBERNETES_APP_DEV_SELECTOR_NAME}=$DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} --namespace=$KUBERNETES_DEV_NAMESPACE
    - kubectl delete pods -l app=${KUBERNETES_APP_DEV_SELECTOR_NAME} --namespace=$KUBERNETES_DEV_NAMESPACE
  only:
    - development

publish-kubernetes-test:
  stage: publish-kubernetes
  image: simpletrading.azurecr.io/monfex/simple-trading-kubectl:latest
  services:
    - docker:dind
  before_script:
    - kubectl config use-context $KUBERNETES_TEST_CONTEXT
  script:
#    - kubectl delete pods -l app=${KUBERNETES_APP_TEST_SELECTOR_NAME} --namespace=$KUBERNETES_TEST_NAMESPACE
    - kubectl set image deployments/${KUBERNETES_APP_TEST_SELECTOR_NAME} ${KUBERNETES_APP_TEST_SELECTOR_NAME}=$DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} --namespace=$KUBERNETES_TEST_NAMESPACE
    - kubectl patch deployment ${KUBERNETES_APP_TEST_SELECTOR_NAME} -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --namespace=$KUBERNETES_TEST_NAMESPACE
  only:
    - test
