variables:
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:1  

stages:
  - build
  - test
  - publish

build:
  stage: build
  image: node:lts-alpine
  script:
    - npm i
    - webpack --config webpack.config.js --mode=production --wshost="wss://simpletrading-dev-api.monfex.biz/ws"
  only:
    - master

publish:
  stage: publish
  services:
    - docker:dind    
  script:      
      - echo "$DOCKER_LOGIN"
      - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      - docker build -t ${DOCKER_IMAGE_TAG} .
      - docker push ${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - master

