variables:
  BUILD_VERSION: 1.0.14
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:${BUILD_VERSION}
  DOCKER_DEV_IMAGE_TAG: monfex/simple-trading-web-terminal:dev
  K8S_DEV_APP_SELECTOR: simple-trading-web-terminal
  K8S_DEV_NAMESPACE: simple-trading-dev
  K8S_DEV_CONTEXT: SimpleTradingDevKubernetes
  BUILD_FOLDER: wwwroot

stages:
  - build
  - publish-dev
  - publish
  - publish-k8s-dev

build:
  tags: [monfex]
  stage: build
  image: node:latest
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - test
    - development

publish:
  stage: publish
  tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - test

publish-dev:
  stage: publish-dev
  #tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG}
  image: docker:latest
  only:
    - development

publish-k8s-dev:
  stage: publish-k8s-dev
  image: google/cloud-sdk
  tags: [monfex]
  services:
    - docker:dind
  before_script:
    - kubectl config use-context ${K8S_DEV_CONTEXT}
  script:
    - kubectl delete pods -l app=${K8S_DEV_APP_SELECTOR} --namespace=${K8S_DEV_NAMESPACE}
  only:
    - development