variables:
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:1.0.0
  DOCKER_DEV_IMAGE_TAG: monfex/simple-trading-web-terminal:dev
  BUILD_FOLDER: wwwroot

stages:
  - build
  - publish-dev
  - publish

build:
  tags: [monfex]
  stage: build
  image: node:latest
  script:
    - npm i
    - npm run build -- --wshost=$WEB_SOCKET_CONNECTION_STRING --apistring=$API_CONNECTION_STRING --authapistring=$AUTH_API_CONNECTION_STRING
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - master
    - development

publish:
  stage: publish
  tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - master

publish-dev:
  stage: publish-dev
  #tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build -t $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG}
  image: docker:latest
  only:
    - development
