variables:
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:1  
  BUILD_FOLDER: wwwroot

stages:
  - build
  - test
  - publish

build:
  tags: [monfex]
  stage: build  
  image: node:latest
  script:
    - npm i
    - npm run build -- --wshost=$WEB_SOCKET_CONNECTION_STRING --apistring=$API_CONNECTION_STRING
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - master

publish:
  stage: publish
  services:
    - docker:dind    
  script:      
      - ls ${BUILD_FOLDER}
      - ls
      - echo "$DOCKER_LOGIN"
      - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      - docker build -t ${DOCKER_IMAGE_TAG} .
      - docker push ${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - master

