variables:
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:1  
  BUILD_FOLDER: wwwroot

stages:
  - build
  - test
  - publish

build:
  job: .pre
  stage: build
  image: node:latest
  script:
    - npm i
    - npm run build -- --wshost=$DOCKER_WEB_SOCKER_CONNECTION_STRING
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - master
    
build:
  stage: build
  image: monfex/web-app-hosting:1
  script:
    - COPY ${BUILD_FOLDER} /app

  image: docker:latest
  only:
    - master

publish:
  stage: publish
  services:
    - docker:dind    
  script:      
      - echo "$DOCKER_LOGIN"
      - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      - docker build -t ${DOCKER_IMAGE_TAG} .
      - docker push ${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - master

