name: Release App
on:
  push:
    tags: "*.*.*"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set env var
      id: string
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF_NAME,,})" >> $GITHUB_ENV
        echo "IMAGE=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "DATE=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "TIMESTAMP=$(date --utc +%F.%H%M%S)" >> $GITHUB_ENV
        
    - name: Npm install
      run: npm install

    - name: Npm build
      run: npm run build

    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ./
        repository: my-cfd-platform/${{ env.IMAGE }}
        tags: ${{ env.BRANCH }}
        build_args: BUILD_VERSION=${{ env.BRANCH }}
